// Code generated by ent, DO NOT EDIT.

package ent

import (
	"suwasystem/backend/ent/community"
	"suwasystem/backend/ent/schema"
	"suwasystem/backend/ent/transaction"
	"suwasystem/backend/ent/user"
	"suwasystem/backend/ent/wallet"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	communityFields := schema.Community{}.Fields()
	_ = communityFields
	// communityDescRate is the schema descriptor for rate field.
	communityDescRate := communityFields[2].Descriptor()
	// community.DefaultRate holds the default value on creation for the rate field.
	community.DefaultRate = communityDescRate.Default.(float32)
	// community.RateValidator is a validator for the "rate" field. It is called by the builders before save.
	community.RateValidator = communityDescRate.Validators[0].(func(float32) error)
	// communityDescTax is the schema descriptor for tax field.
	communityDescTax := communityFields[3].Descriptor()
	// community.DefaultTax holds the default value on creation for the tax field.
	community.DefaultTax = communityDescTax.Default.(float32)
	// community.TaxValidator is a validator for the "tax" field. It is called by the builders before save.
	community.TaxValidator = communityDescTax.Validators[0].(func(float32) error)
	// communityDescCreatedAt is the schema descriptor for created_at field.
	communityDescCreatedAt := communityFields[4].Descriptor()
	// community.DefaultCreatedAt holds the default value on creation for the created_at field.
	community.DefaultCreatedAt = communityDescCreatedAt.Default.(func() time.Time)
	// communityDescUpdatedAt is the schema descriptor for updated_at field.
	communityDescUpdatedAt := communityFields[5].Descriptor()
	// community.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	community.DefaultUpdatedAt = communityDescUpdatedAt.Default.(func() time.Time)
	// community.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	community.UpdateDefaultUpdatedAt = communityDescUpdatedAt.UpdateDefault.(func() time.Time)
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescAmount is the schema descriptor for amount field.
	transactionDescAmount := transactionFields[1].Descriptor()
	// transaction.AmountValidator is a validator for the "amount" field. It is called by the builders before save.
	transaction.AmountValidator = transactionDescAmount.Validators[0].(func(int) error)
	// transactionDescTax is the schema descriptor for tax field.
	transactionDescTax := transactionFields[2].Descriptor()
	// transaction.DefaultTax holds the default value on creation for the tax field.
	transaction.DefaultTax = transactionDescTax.Default.(int)
	// transaction.TaxValidator is a validator for the "tax" field. It is called by the builders before save.
	transaction.TaxValidator = transactionDescTax.Validators[0].(func(int) error)
	// transactionDescTotalAmount is the schema descriptor for total_amount field.
	transactionDescTotalAmount := transactionFields[3].Descriptor()
	// transaction.TotalAmountValidator is a validator for the "total_amount" field. It is called by the builders before save.
	transaction.TotalAmountValidator = transactionDescTotalAmount.Validators[0].(func(int) error)
	// transactionDescTransactionDate is the schema descriptor for transaction_date field.
	transactionDescTransactionDate := transactionFields[4].Descriptor()
	// transaction.DefaultTransactionDate holds the default value on creation for the transaction_date field.
	transaction.DefaultTransactionDate = transactionDescTransactionDate.Default.(func() time.Time)
	// transactionDescID is the schema descriptor for id field.
	transactionDescID := transactionFields[0].Descriptor()
	// transaction.DefaultID holds the default value on creation for the id field.
	transaction.DefaultID = transactionDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[4].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[5].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	walletFields := schema.Wallet{}.Fields()
	_ = walletFields
	// walletDescBalance is the schema descriptor for balance field.
	walletDescBalance := walletFields[0].Descriptor()
	// wallet.DefaultBalance holds the default value on creation for the balance field.
	wallet.DefaultBalance = walletDescBalance.Default.(int)
	// wallet.BalanceValidator is a validator for the "balance" field. It is called by the builders before save.
	wallet.BalanceValidator = walletDescBalance.Validators[0].(func(int) error)
	// walletDescCreatedAt is the schema descriptor for created_at field.
	walletDescCreatedAt := walletFields[1].Descriptor()
	// wallet.DefaultCreatedAt holds the default value on creation for the created_at field.
	wallet.DefaultCreatedAt = walletDescCreatedAt.Default.(func() time.Time)
	// walletDescUpdatedAt is the schema descriptor for updated_at field.
	walletDescUpdatedAt := walletFields[2].Descriptor()
	// wallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	wallet.DefaultUpdatedAt = walletDescUpdatedAt.Default.(func() time.Time)
	// wallet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	wallet.UpdateDefaultUpdatedAt = walletDescUpdatedAt.UpdateDefault.(func() time.Time)
}
